repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.6
  hooks:
    - id: ruff
      args: ["format", "."]
    - id: ruff
      args: ["check", ".", "--fix"]
    - id: ruff
      args: ["check", ".", "--fix", "--select", "I"]