repos:
  - repo: local
    hooks:
      - id: ruff-all
        name: ruff format + fix + imports
        entry: bash -c '
          set -e
          poetry run ruff format .
          poetry run ruff check --fix .
          poetry run ruff check --fix --select I
          '
        language: system
        types: [python]
        pass_filenames: false