[project]
name = "drfbooking"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "max.b04.03@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django (>=5.2.4,<6.0.0)",
]


[tool.poetry.group.local]
optional = true

[tool.poetry.group.local.dependencies]
pre-commit = "^4.2.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
