default:
  SECRET_KEY: ""
  DEBUG: true
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost

  APP_PORT: 8000

  POSTGRES_DB: ""
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST: ""
  POSTGRES_PORT: 5432

local:
  POSTGRES_HOST: localhost
development:
  POSTGRES_HOST: db-dev
test:
  POSTGRES_HOST: db-test
