# Generated by Django 5.2.4 on 2025-08-02 06:11

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("f6ff8d54-33aa-41b8-9d3c-b5d48698df84"),
                        editable=False,
                        help_text="ID номера в БД.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField(help_text="Описание номера.")),
                (
                    "price_per_night",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Цена за ночь за номер.",
                        max_digits=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Дата и время добавления номера."
                    ),
                ),
            ],
        ),
    ]
