# Generated by Django 5.2.4 on 2025-08-02 06:49

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="ID брони в БД.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date_start",
                    models.DateField(help_text="Дата начала действия брони."),
                ),
                (
                    "date_end",
                    models.DateField(help_text="Дата окончания действия брони."),
                ),
                (
                    "room",
                    models.ForeignKey(
                        help_text="Номер, на который оформлена бронь, в БД.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="room.room",
                    ),
                ),
            ],
        ),
    ]
