name: PR into main branch check and fix

on:
  pull_request:
    branches: [main]

jobs:
  format_check_and_fix:
    name: Ruff check and fix
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies with Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-interaction --no-ansi --with dev

      - name: Run Ruff format and fix (via Poetry)
        run: |
          poetry run ruff format .
          poetry run ruff check --fix .

      - name: Commit fixes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if [[ $(git status --porcelain) ]]; then
            git add .
            git commit -m "style: auto-fix code with Ruff"
            git push origin HEAD:${{ github.head_ref }}
          else
            echo "No changes to commit"
          fi
  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: format_check_and_fix
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies with Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-interaction --no-ansi
          eval $(poetry env activate)

      - name: Tests in Docker Containers
        run: |
          make test